name: Android CI

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set App Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=Weather" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Run Build Project (Debug)
      - name: Build gradle project (Debug)
        run: ./gradlew assembleDebug

      # Upload Artifact Build
      - name: Upload Debug APK - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repository_name }} - ${{ env.date_today }} - Debug APK generated
          path: app/build/outputs/apk/debug/
